name: linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Golint:
    runs-on: ubuntu-18.04
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v2
      - name: "Lint Go Code"
        uses: golangci/golangci-lint-action@v2
        with:
            version: v1.29
