name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  soccer-api-go:
    runs-on: ubuntu-18.04
    strategy:
        matrix:
          go: [ '1.15' ]
    services:
      mysql:
        image: mysql:5.7
        env:
            MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
            MYSQL_USER: ${{ secrets.MYSQL_USER }}
            MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
            MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        ports:
            - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: "Set up Go"
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: "Check out source code"
        uses: actions/checkout@v2
      - name: Download dependency
        run: make vendor
      - name: Run all test
        run: make test
